### ISSUE TITLE
2019/05 DockerCon US 2019

### ISSUE THREAD

**Issue by vcoisne** [src-d/conferences#119]
**URL**: 2019.dockercon.com (Not live yet)

**Location**: San Francisco, CA

**Dates**: 2019/04/29- 2019/05/2

**Expenses covered**: Not needed for Francesc

**Topic**:  containers, Kubernetes, Docker

**Call for Papers**:

deadline: 2019/01/18
link:  https://dockercon19.smarteventscloud.com/portal/cfp/home.ww

**Notes**:

I think we should submit a talk on a YAML / Dockerfile bblfsh parser cc @campoy ?

**Comment by vcoisne** [comment]
@campoy following our conversation with Garreth,  It would be cool to submit a talk on parsing Dockerfile and YAML files. WDYT ?

**Comment by campoy** [comment]
Definitely agreed, but probably checking with @creachadair first.

If I recall correctly there were some doubts about whether a YAML parser for Bblfsh would make sense at all.

**Comment by creachadair** [comment]
> If I recall correctly there were some doubts about whether a YAML parser for Bblfsh would make sense at all.

I don't see any immediate reason _against_ having a Babelfish parser for YAML. The main difficulty with these metasyntactic languages like JSON and YAML is that their surface grammar is rarely the one you really care about. In other words, you rarely want to do operations on arbitrary JSON (say), vs. "the JSON corresponding to kubectl request messages" or some other concrete grammar that uses JSON as a transport.

I imagine even the surface structure could be useful in some cases, but I don't really foresee that being very general-purpose, since any tool that wants to reason about the concrete grammar is going to have to have knowledge of that grammar already. This in contrast to languages with classified structures where you can get value out of knowing the shape of functions, variables, conditionals, etc., without having to know exactly how they're encoded.

Dockerfile might be a better case: Both because it's more specific, and because it's smaller.

**Comment by campoy** [comment]
I would like to be able to perform analyses on both json and yaml eventually, but I'm not completely sure what's the best way to get there.

Bbblfsh parsers would be a way, an alternative would be some kind of MySQL custom functions, which once we have UDFs should be relatively easy to add.

@mcuadros, what do you think about all this?

**Comment by campoy** [comment]
Ended up not proposing anything, but I might consider attending.

For now I'm closing the issue.
