### ISSUE TITLE
2019/04 - AI Meetup Paris

### ISSUE THREAD

**Issue by warenlg** [src-d/conferences#140]
**URL**: https://www.meetup.com/Artificial-Intelligence-Meetup-Paris

**Location**: Paris, France

**Dates**: 2019/04/18

**Expenses covered**: No. I would stay home though, and would only need the flights (~100 EUR)

**Topic**:   The meetup is focused on new tech stacks available in AI and the use cases around AI. Thy usually invite exciting startups who are working in AI and present their technology.

**Call for Papers**:

deadline: not specified

**Notes**:

I've been invited by the organizer by email to give 1 of the 3 talks of the evening. I could extend my presentation done last week https://warenlg.github.io/ai-society-2019-paris/# 
The meetup is organized by SAP in LeBonCoin's office. Last time more than 100 people attended. The talks are usually done by senior engineers so I expect the meetup to be quite technical with big companies in the audience.

**Comment by vcoisne** [comment]
@warenlg I think this is a great opportunity. definitely worth the $100.

**Comment by bzz** [comment]
@warenlg thank you for sharing slides https://warenlg.github.io/ai-society-2019-paris/# in advance, just in case is there any followup materials worth linking in as well? If so, please feel free to those post here.

Otherwise, as there is no further discussion I'll take a liberty and close this one, as it's been at least 1 month after the event.
